name: bdm_sport
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.9.0
  cupertino_icons: ^1.0.8
  ionicons: ^0.2.1
  go_router: ^16.1.0
  intl: ^0.20.2
  flutter_vector_icons: ^2.0.0
  url_launcher: ^6.3.2
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.1.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  flutter_riverpod: ^2.6.1
  fluttertoast: ^8.2.12
  firebase_storage: ^13.0.0
  image_picker: ^1.1.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true
